__title__ = 'spectrum-client'
__description__ = 'CA Spectrum Web Services API wrapper.'
__url__ = 'https://github.com/orgito/spectrum-client'
__version__ = '0.3.0'
__author__ = 'Renato Orgito'
__author_email__ = 'orgito@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Renato Orgito'
